# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# Start AeroSpace at login
start-at-login = true

# You can use it to add commands that run after AeroSpace startup.
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
    'exec-and-forget pkill -x border',
    'exec-and-forget /opt/homebrew/bin/borders active_color=0xFF38DFED inactive_color=0xFF536872 width=8.0'
]

exec-on-workspace-change = [
    '/bin/bash',
    '-c',
    'sketchybar --trigger aerospace_workspace_changed FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]


# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = [
  'move-mouse monitor-lazy-center'
]

on-focus-changed = [
  'move-mouse window-lazy-center',
  'exec-and-forget /bin/bash -c /opt/homebrew/bin/sketchybar --trigger front_app_switched',
  'exec-and-forget sketchybar --trigger update_windows'
]

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# Possible values: (qwerty|dvorak|colemak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
    preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
    inner.horizontal = 12
    inner.vertical =   12
    outer.left =       12
    outer.bottom =     12
    outer.top =        [{monitor.'^built-in retina display$' = 20 }, 48]
    outer.right =      12

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]
    # All possible keys:
    # - Letters.        a, b, c, ..., z
    # - Numbers.        0, 1, 2, ..., 9
    # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
    # - F-keys.         f1, f2, ..., f20
    # - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
    #                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
    #                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
    #                   sectionSign (ISO keyboards only, european keyboards only)
    # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
    #                   keypadMinus, keypadMultiply, keypadPlus
    # - Arrows.         left, down, up, right

    # All possible modifiers: cmd, alt, ctrl, shift

    # All possible commands: https://nikitabobko.github.io/AeroSpace/commands

    # See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
    # You can uncomment the following lines to open up terminal with alt + enter shortcut
    # (like in i3)
    # alt-enter = '''exec-and-forget osascript -e '
    # tell application "Terminal"
    #     do script
    #     activate
    # end tell'
    # '''

    alt-a = [
        'mode moonlander',
        'exec-and-forget sketchybar --trigger send_message MESSAGE="MOONLANDER MODE" HOLD="true"'
    ]

    alt-shift-semicolon = [
        'mode service',
        'exec-and-forget sketchybar --trigger send_message MESSAGE="SERVICE MODE" HOLD="true"'
    ]
    alt-w = [
        'mode resize',
        'exec-and-forget sketchybar --trigger send_message MESSAGE="RESIZE MODE" HOLD="true"'
    ]

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
    alt-ctrl-tab = 'workspace-back-and-forth'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    cmd-shift-h = 'move left'
    cmd-shift-j = 'move down'
    cmd-shift-k = 'move up'
    cmd-shift-l = 'move right'

    # ------------ For the laptop ------------

    alt-slash = ['layout tiles horizontal vertical', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    alt-shift-slash = ['layout accordion horizontal vertical', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']

    # See: https://nikitabobko.github.io/AeroSpace/commands#focus
    alt-h = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop left'
    alt-j = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop down'
    alt-k = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop up'
    alt-l = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop right'

    alt-comma = 'focus-monitor --wrap-around prev'
    alt-period = 'focus-monitor --wrap-around next'

    alt-shift-comma = 'move-workspace-to-monitor --wrap-around left'
    alt-shift-period = 'move-workspace-to-monitor --wrap-around right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    alt-shift-h = 'join-with left'
    alt-shift-j = 'join-with down'
    alt-shift-k = 'join-with up' 
    alt-shift-l = 'join-with right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'
    alt-0 = 'workspace 10'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'
    alt-shift-0 = 'move-node-to-workspace 10'

    # See: https://nikitabobko.github.io/AeroSpace/commands#mode
    # Modes
    # My customizations
    alt-g = 'layout floating tiling'
    alt-m = 'fullscreen'

[mode.moonlander.binding]
    # --------- For Moonlander ----------

    # See: https://nikitabobko.github.io/AeroSpace/commands#layout
    slash = ['layout tiles horizontal vertical', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    shift-slash = ['layout accordion horizontal vertical', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']

    # See: https://nikitabobko.github.io/AeroSpace/commands#focus
    h = ['focus --boundaries all-monitors-outer-frame --boundaries-action stop left', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    j = ['focus --boundaries all-monitors-outer-frame --boundaries-action stop down', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    k = ['focus --boundaries all-monitors-outer-frame --boundaries-action stop up', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    l = ['focus --boundaries all-monitors-outer-frame --boundaries-action stop right', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']

    comma = ['focus-monitor --wrap-around prev', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    period = ['focus-monitor --wrap-around next', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']

    shift-comma = ['move-workspace-to-monitor --wrap-around left', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    shift-period = ['move-workspace-to-monitor --wrap-around right', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']

    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    minus = ['resize smart -50', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    equal = ['resize smart +50', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']

    shift-h = ['join-with left', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    shift-j = ['join-with down', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    shift-k = ['join-with up' , 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    shift-l = ['join-with right', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
    1 = ['workspace 1', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    2 = ['workspace 2', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    3 = ['workspace 3', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    4 = ['workspace 4', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    5 = ['workspace 5', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    6 = ['workspace 6', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    7 = ['workspace 7', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    8 = ['workspace 8', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    9 = ['workspace 9', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    0 = ['workspace 10', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']

    # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
    shift-1 = ['move-node-to-workspace 1', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    shift-2 = ['move-node-to-workspace 2', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    shift-3 = ['move-node-to-workspace 3', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    shift-4 = ['move-node-to-workspace 4', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    shift-5 = ['move-node-to-workspace 5', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    shift-6 = ['move-node-to-workspace 6', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    shift-7 = ['move-node-to-workspace 7', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    shift-8 = ['move-node-to-workspace 8', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    shift-9 = ['move-node-to-workspace 9', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
    shift-0 = ['move-node-to-workspace 10', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']

    # See: https://nikitabobko.github.io/AeroSpace/commands#mode
    # Modes
    # My customizations
    g = ['layout floating tiling', 'mode main', 'exec-and-forget sketchybar --trigger hide_message'] # Toggle between floating and tiling layout
    m = ['fullscreen', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']

    esc = [
        'mode main',
        'exec-and-forget sketchybar --trigger hide_message'
    ]

[workspace-to-monitor-force-assignment]
    1 = 'main'
    8 = [1, 'main']
    9 = 3
    10 = [3, 1]

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
    esc = [
        'reload-config',
        'mode main',
        'exec-and-forget sketchybar --trigger hide_message'
    ]
    r = ['flatten-workspace-tree', 'mode main', 'exec-and-forget sketchybar --trigger hide_message'] # reset layout
    backspace = ['close-all-windows-but-current', 'mode main', 'exec-and-forget sketchybar --trigger hide_message' ]

    # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
    #s = ['layout sticky tiling', 'mode main']

    down = 'volume down'
    up = 'volume up'
    shift-down = ['volume set 0', 'mode main']

[mode.resize.binding]
    h = ['resize width -64']
    j = ['resize height -64']
    k = ['resize height +64']
    l = ['resize width +64']
    n = ['balance-sizes']
    esc = [
      'mode main',
      'exec-and-forget sketchybar --trigger hide_message'
    ]
